server:
  port: 8888

spring:
  application:
    name: play-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/YOUR_GITHUB/config-repo
          clone-on-start: true
